addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.9")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"             % "0.9.3")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.1.0")
addSbtPlugin("com.lightbend.sbt" % "sbt-java-formatter"  % "0.4.1")
addSbtPlugin("com.typesafe.sbt"  % "sbt-license-report"  % "1.2.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.3.15")
addSbtPlugin("io.spray"          % "sbt-revolver"        % "0.9.1")
